### ISSUE TITLE
Hintergrundfarbe

### ISSUE THREAD

**Issue by TommyEwald** [TommyEwald/Quick-E-Quiz#10]
wird auf dem Tab von Herrn Höhne nicht angezeigt

**Comment by PascalHelbig** [comment]
Weißt du zufällig welche Android Version auf dem Tablet läuft? Vielleicht ist das die Fehlerursache.

**Comment by NikCas** [comment]
4.1 oder 4.2?

**Comment by TommyEwald** [comment]
Ist eine sehr alte.. glaube es war kitkat

NikCas notifications@github.com schrieb am Mi., 13. Apr. 2016 16:20:
